name: Codeowners merging
on:
  pull_request_target: { types: [opened] }
  issue_comment: { types: [created] }
  pull_request_review: { types: [submitted] }

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Codeowners merge check
        uses: OSS-Docs-Tools/code-owner-self-merge@1.6.8
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
