name: Sync Discord Roles

on:
  pull_request:
    types: [closed]
  workflow_dispatch: {}

jobs:
  assign-role:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Assign role via Discord bot
        run: python syncrole.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          ROLE_ID: ${{ secrets.ROLE_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

